### ISSUE TITLE
Changing the comment's color for a better contrast on the dark theme?

### ISSUE THREAD

**Issue by borislavib** [anler/minimal-theme#2]
@anler  great theme, just one question, actually it's not an issue.
When it comes to the dark theme,  the comment is `(comment "grey25")`.  How do I change it to other shade of let's say some lighter shade of blue ? `blue10` and `blue90` seems to be the same color ?

**Comment by anler** [comment]
Hi @borislavib you can change it with this snippet of code:

```emacs-lisp
(custom-theme-set-faces
 'minimal
 `(font-lock-comment-face ((nil (:foreground "blue90")))))
```

maybe I should change the color to `grey35` or something because I agree it's hard to see with the current value
